In [1]:
import sympy as sp
from ham_to_matrix import *
from constants import *

## Diagonal Part

In [2]:
totHam = pn**2 + qn**2

In [3]:
totHam

p_{n}**2 + q_{n}**2

In [4]:
N=3
aVal=1

# depends on finite-difference method
qs=[SiteSymbol('q',str(i)) for i in range(-1,N+1,1)]
ps=[SiteSymbol('p',str(i)) for i in range(-1,N+1,1)] # don't really need extras
aops=[SiteSymbol('a',str(i)) for i in range(-1,N+1,1)]
adags=[SiteSymbol('a^{\dagger}',str(i)) for i in range(-1,N+1,1)]

# note this is exactly hardcoded for this finite difference method.
bcType = 'periodic'
boundaryConditions = {}

# warning be careful of array indexing...   
if bcType == 'periodic':
    boundaryConditions = {qs[0]: qs[N], qs[N+1]: qs[1]
                         }
elif bcType == 'dirichlet':
    boundaryConditions = {qs[0]: 0, qs[N+1]: 0}

In [5]:
s=''
for q in qs:
    s+='{}  '.format(q)
print(s)
qs[0]

q_{-1}  q_{0}  q_{1}  q_{2}  q_{3}  


q_{-1}

In [6]:
ham=0
for i in range(1,N+1):
    ham+=totHam.subs({qn: qs[i], pn: ps[i]}).subs(boundaryConditions)

ham

p_{0}**2 + p_{1}**2 + p_{2}**2 + q_{0}**2 + q_{1}**2 + q_{2}**2

In [7]:
m=1

HOdofSubs = {}
#offset because of BC
for i in range(1,N+1):
    HOdofSubs[qs[i]] = 0.5*sp.sqrt(2/m)*(aops[i] + adags[i])
    HOdofSubs[ps[i]] = complex(0,1)*sp.sqrt(2*m)*(adags[i] - aops[i])/2 

hoHam=sp.expand(ham.subs(HOdofSubs))
hoHam=sp.nsimplify(hoHam,tolerance=1e-8)
hoHam

a^{\dagger}_{0}*a_{0} + a^{\dagger}_{1}*a_{1} + a^{\dagger}_{2}*a_{2} + a_{0}*a^{\dagger}_{0} + a_{1}*a^{\dagger}_{1} + a_{2}*a^{\dagger}_{2}

In [8]:
print(hoHam.args[0])
for a in hoHam.args[0].args:
    print(a.name)

a^{\dagger}_{0}*a_{0}
a^{\dagger}_{0}
a_{0}


In [9]:
convert_boson_term_to_matrix(hoHam.args[0],4,3,aops,adags)

[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]


array([[0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       ...,
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, ..., 0.+0.j, 0.+0.j, 0.+0.j]])

In [10]:
cutoff=4
hamMat=convert_boson_to_matrix(hoHam,cutoff,N,aops,adags)

[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [1.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 1.4142135+0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.7320508+0.j 0.       +0.j]]
[[0.       +0.j 0.       +0.j 0.       +0.j 0.      

In [11]:
hamMat

array([[0.        +0.j, 1.        +0.j, 0.        +0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [1.        +0.j, 0.        +0.j, 1.41421354+0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 1.41421354+0.j, 0.        +0.j, ...,
        0.        +0.j, 0.        +0.j, 0.        +0.j],
       ...,
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.        +0.j, 1.41421354+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        1.41421354+0.j, 0.        +0.j, 1.73205078+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, ...,
        0.        +0.j, 1.73205078+0.j, 0.        +0.j]])

In [12]:
cutoff=4
hamMat=convert_boson_to_matrix(hoHam,cutoff,N,aops,adags)
ens=np.sort(np.linalg.eig(hamMat.astype(np.complex64))[0])
ens=ens.round(8)

np.isreal(ens).all()

ens

[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [1.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 1.4142135+0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.7320508+0.j 0.       +0.j]]
[[0.       +0.j 0.       +0.j 0.       +0.j 0.      

array([-7.003242  +0.j, -5.4107924 -0.j, -5.4107924 -0.j, -5.4107924 +0.j,
       -3.9268646 -0.j, -3.9268646 -0.j, -3.9268646 +0.j, -3.8183417 -0.j,
       -3.8183417 -0.j, -3.8183417 +0.j, -2.3344142 -0.j, -2.3344142 -0.j,
       -2.3344142 -0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j,
       -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.2258914 +0.j,
       -0.85048664-0.j, -0.85048664+0.j, -0.85048664+0.j, -0.74196386-0.j,
       -0.74196386-0.j, -0.74196386-0.j, -0.74196386-0.j, -0.74196386-0.j,
       -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        0.74196386+0.j,  0.85048664-0.j,  0.85048664+0.j,  0.85048664+0.j,
        2.2258914 -0.j,  2.3344142 -0.j,  2.3344142 -0.j,  2.3344142 -0.j,
        2.3344142 -0.j,  2.3344142 +0.j,  2.3344142 +0.j,  2.3344142 +0.j,
        2.3344142 +0.j,  

In [13]:
cutoff=4
hamMat=convert_boson_to_matrix(hoHam.args[0]+hoHam.args[3],cutoff,N,aops,adags)
print(hamMat)
ens=np.sort(np.linalg.eig(hamMat.astype(np.complex64))[0])
ens=ens.round(8)

np.isreal(ens).all()

ens

[[0.       +0.j 1.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.4142135+0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 1.7320508+0.j]
 [0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]]
[[0.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [1.       +0.j 0.       +0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 1.4142135+0.j 0.       +0.j 0.       +0.j]
 [0.       +0.j 0.       +0.j 1.7320508+0.j 0.       +0.j]]
[[0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 ...
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j ... 0.+0.j 0.+0.j 0.+0.j]]


array([-2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j,
       -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j,
       -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j,
       -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j, -2.3344142 +0.j,
       -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j,
       -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j,
       -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j,
       -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j, -0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,  0.74196386+0.j,
        2.3344142 +0.j,  2.3344142 +0.j,  2.3344142 +0.j,  2.3344142 +0.j,
        2.3344142 +0.j,  

In [14]:
np.kron(1,np.array([[1,0],[0,1]]))

array([[1, 0],
       [0, 1]])

## Full boson part

In [15]:
bosonNI=sp.expand( p[n]**2/(2*aLat) + (aLat/2)*((q[n+1]-q[n-1])/(2*aLat))**2 )
bosonI=sp.expand( (aLat/2)*V(q[n])**2 + aLat*V(q[n])*(q[n+1]-q[n-1])/(2*aLat) )

ham=0
totHam=bosonNI+bosonI
totHam

TypeError: 'SiteSymbol' object is not subscriptable

In [ ]:
N=3
aVal=1

# note this is exactly hardcoded for this finite difference method.
bcType = 'periodic'
boundaryConditions = {}
if bcType == 'periodic':
    boundaryConditions = {q[-1]: q[N-1], q[N]: q[0],
                          x[N]: x[0], xd[N]: xd[0],
                         }
elif bcType == 'dirichlet':
    boundaryConditions = {q[-1]: 0, q[N]: 0,
                          x[N]: 0, xd[N]: 0
                         }

In [ ]:

for i in range(0,N):
    ham+=totHam.subs(n,i).subs(boundaryConditions)
# ham.subs(boundaryConditions).doit() # this doesn't work?

def potential(n):
    return 0

for n in range(0,N):
    ham=ham.subs(V(q[n]),potential(n))
ham=ham.subs(aLat,aVal).simplify().expand()
ham

In [ ]:
m=1

HOdofSubs = {}
for i in range(0,N):
    HOdofSubs[q[i]] = 0.5*sp.sqrt(2/m)*(a[i] + adag[i])
    HOdofSubs[p[i]] = complex(0,1)*sp.sqrt(2*m)*(adag[i] - a[i])/2
    
hoHam=sp.expand(ham.subs(HOdofSubs))
sp.nsimplify(hoHam,tolerance=1e-10)

In [ ]:
cutoff=4
hamMat=convert_to_matrix(hoHam,cutoff,N)

In [ ]:
hamMat.shape

In [ ]:
np.isreal(hamMat).all()

In [ ]:
(hamMat==np.matrix(hamMat).H).all()

In [ ]:
np.sort(np.linalg.eig(hamMat.astype(np.complex64))[0])

In [ ]:
m=convert_term_to_matrix(1.0*a[0]*a[1], 4, 3).astype(float)

In [ ]:
for row in m:
    print(row)