In [1]:
import sympy as sp
from ham_to_matrix import *
from constants import *

In [2]:
a[0]*a[0]

a[0]**2

In [19]:
m=convert_term_to_matrix(1.0*a[0]*a[0], 4, 3).astype(float)
print(m.shape)

(512, 512)


In [20]:
#for r in m:
#    for elem in r:
#        if not np.isclose(elem,0):
#            print(elem)

In [23]:
np.linalg.matrix_power(aMat(4),2)

array([[0.        , 0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        , 2.44948974],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [24]:
m[0:4,0:4]

array([[0.        , 0.        , 1.41421354, 0.        ],
       [0.        , 0.        , 0.        , 2.44948959],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [27]:
(m[4:m.shape[0],4:m.shape[0]]==np.eye(m.shape[0]-4)).all()

True

In [11]:
cutoff=2
Nsites=3
fullHam = np.zeros([(cutoff**Nsites)*(2**Nsites),(cutoff**Nsites)*(2**Nsites)]).astype(np.complex64)

In [12]:
fullHam.shape

(64, 64)

In [13]:
aMat(cutoff)

array([[0., 1.],
       [0., 0.]])

In [14]:
aMat(2)

array([[0., 1.],
       [0., 0.]])

In [15]:
np.array([[0,1,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,1]])

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [16]:
np.tensordot(aMat(2),np.eye(2),0) # c_{ijkl}

array([[[[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [0., 1.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [17]:
np.kron(aMat(2),np.eye(2))

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.kron(np.eye(2),aMat(2))

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])