In [1]:
import sympy as sp
from ham_to_matrix import *
from constants import *

In [2]:
a[0]*a[0]

a[0]**2

In [30]:
m=convert_term_to_matrix(1.0*a[0]*a[0], 6, 3).astype(float)
print(m.shape)

KeyboardInterrupt: 

In [11]:
#for r in m:
#    for elem in r:
#        if not np.isclose(elem,0):
#            print(elem)

In [5]:
np.matmul(aMat(2),aMat(2))

array([[0., 0.],
       [0., 0.]])

In [6]:
np.matmul(aMat(4),aMat(4))

array([[0.        , 0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        , 2.44948974],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [7]:
np.linalg.matrix_power(aMat(4),2)

array([[0.        , 0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        , 2.44948974],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [8]:
m[0:4,0:4]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.matmul(aMat(6),aMat(6))[0:4,0:4]

array([[0.        , 0.        , 1.41421356, 0.        ],
       [0.        , 0.        , 0.        , 2.44948974],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

In [44]:
((2**5)*(8**5))**2

1099511627776

In [41]:
cutoff=8
Nsites=5
fullHam = np.zeros([(cutoff**Nsites)*(2**Nsites),(cutoff**Nsites)*(2**Nsites)]).astype(np.complex64)

MemoryError: Unable to allocate 8.00 TiB for an array with shape (1048576, 1048576) and data type float64

In [36]:
fullHam.shape

(4096, 4096)

In [18]:
aMat(cutoff)

array([[0., 1.],
       [0., 0.]])

In [ ]:

aMatIndices=[ (siteOffset + i) for i in range(cutoff) ]
for i in fullHam.shape[0]:
    for j in fullHam.shape[1]:
        if (i not in aMatIndices) and (j not in aMatIndices):
            # fill with amat values ( i 40)
            # subtract offset from i to get index in aMat
            # 40-38 = 2 aMat[2,2]
        else:
            # fill with identity matrix. 

In [29]:
aMat(2)

array([[0., 1.],
       [0., 0.]])

In [28]:
np.array([[0,1,0,0],[0,0,0,0],[0,0,1,0],[0,0,0,1]])

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [26]:
np.tensordot(aMat(2),np.eye(2),0) # c_{ijkl}

array([[[[0., 0.],
         [0., 0.]],

        [[1., 0.],
         [0., 1.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [24]:
np.kron(aMat(2),np.eye(2))

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.kron(np.eye(2),aMat(2))

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])